stages:
  - build
  - test

# 1. Собираем JAR
build:
  stage: build
  image: eclipse-temurin:21
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

# 2. Проверка зависимостей (SCA)
dependency_check:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - ./mvnw org.owasp:dependency-check-maven:check
  artifacts:
    when: always
    paths:
      - target/dependency-check-report.html

# 3. Статический анализ (SAST) через Semgrep
semgrep:
  stage: test
  image: semgrep/semgrep
  script:
    - semgrep --config=auto --json --output results.json
  artifacts:
    paths:
      - results.json

# 4. Динамический анализ (DAST) - Базовый
dast_baseline:
  stage: test
  image:
    name: zaproxy/zap-stable
    entrypoint: [""]
  needs:
    - build
  before_script:
    - touch rules.tsv
  script:
    # Устанавливаем Java, чтобы запустить твой JAR внутри контейнера ZAP
    - apt-get update && apt-get install -y openjdk-17-jr
    - java -jar target/*.jar &
    - sleep 30
    - zap-baseline.py -t http://localhost:8080 -c rules.tsv -r report_baseline.html
  artifacts:
    when: always
    paths:
      - report_baseline.html

# 5. Динамический анализ (DAST) - API
dast_api:
  stage: test
  image:
    name: zaproxy/zap-stable
    entrypoint: [""]
  needs:
    - build
  before_script:
    - touch rules.tsv
  script:
    - apt-get update && apt-get install -y openjdk-17-jr
    - java -jar target/*.jar &
    - sleep 30
    - zap-api-scan.py -t http://localhost:8080/v3/api-docs -f openapi -c rules.tsv -r report_api.html
  artifacts:
    when: always
    paths:
      - report_api.html