stages:
  - secrets-scan
  - build
  - test
  - fuzzing

# 1. ПОИСК СЕКРЕТОВ (Gitleaks)
gitleaks:
  stage: secrets-scan
  image:
    name: gitleaks/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . -v
  artifacts:
    when: always
    paths:
      - gitleaks-report.json

# 2. СБОРКА
build:
  stage: build
  image: eclipse-temurin:21
  needs:
    - gitleaks
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

# 3. ПРОВЕРКА ЗАВИСИМОСТЕЙ (SCA)
dependency_check:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - chmod +x mvnw
    - ./mvnw org.owasp:dependency-check-maven:check || true
  artifacts:
    when: always
    paths:
      - target/dependency-check-report.html

# 4. СТАТИЧЕСКИЙ АНАЛИЗ (SAST)
semgrep:
  stage: test
  image: semgrep/semgrep
  script:
    - semgrep --config=auto --json --output results.json .
  artifacts:
    paths:
      - results.json

# 5. ДИНАМИЧЕСКИЙ АНАЛИЗ (DAST)
dast_baseline:
  stage: test
  image:
    name: zaproxy/zap-stable
    entrypoint: [""]
  needs:
    - build
  script:
    - apt-get update && apt-get install -y openjdk-17-jre
    - java -jar target/*.jar > app.log 2>&1 &
    - sleep 40
    - zap-baseline.py -t http://localhost:8080 -r report_baseline.html || true
  artifacts:
    when: always
    paths:
      - report_baseline.html
      - app.log

# 6. ФАЗЗИНГ-ТЕСТИРОВАНИЕ (ffuf)
web_fuzzing:
  stage: fuzzing
  image:
    name: ffuf/ffuf
    entrypoint: [""]
  needs:
    - build
  script:
    - apt-get update && apt-get install -y openjdk-17-jre
    - java -jar target/*.jar > app.log 2>&1 &
    - sleep 40
    - echo -e "admin\napi\nconfig\n.env\nbackup\nsecret\ndev\nlogin" > wordlist.txt
    - ffuf -u http://localhost:8080/FUZZ -w wordlist.txt -mc 200,403,401 -o fuzz-results.json
  artifacts:
    when: always
    paths:
      - fuzz-results.json
      - app.log